### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by artin** [azdyb/gnome-shell-extension-netmonitor#1]
I tried both manual ( using terminal ) automatic ( using gnome-tweak-tool)  but  both result in crashing gnome shell and I have to restart shell in console .

I am using Ubuntu 11.10 64bit with Gnome 3.2.0

I didn't find any log about it.

Thanks

**Comment by azdyb** [comment]
Thank you for the report. Gnome 3.2 is not supported at the time (see NetMonitor@zdyb.tk/metadata.json), but I'm working on it. One may expect update very soon.

**Comment by azdyb** [comment]
I've just updated extension to support GNOME 3.2.
