### ISSUE TITLE
GTop required

### ISSUE THREAD

**Issue by muCkk** [azdyb/gnome-shell-extension-netmonitor#2]
Hey,

I just installed NetMonitor but I can't get rid of this error (displayed in the debugging-console):
Error: Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found

Nice extension btw :)

**Comment by azdyb** [comment]
Thank you for your submission. It seems that you don't have gir for libgtop (or maybe libgtop itself) installed. I don't believe the extension will work without it. Please make sure you have the appropriate libraries installed.

**Comment by muCkk** [comment]
Just checked it out, I have libgtop2-7 and libgtop2-common installed. Do I need anything else?

Edit: libgtop-dev did it. Thanks!

**Comment by azdyb** [comment]
Check for existance of the following files:
    /usr/lib64/girepository-1.0/GTop-2.0.typelib
    /usr/share/gir-1.0/GTop-2.0.gir

Note, that the files may be placed in different locations depending on your distro (mine is Fedora 16).

**Comment by cherrot** [comment]
Actually, It's gir1.2-gtop-2.0 which works. 
However, this package will break the translation of gnome-shell. Weired. :(
